version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-golang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qorxaed3se58"
s3_prefix = "sam-golang"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
