import { expect, test } from '@playwright/test'

test('TODO lifecycle survives reload and filters correctly', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '今日を、ひとつずつ。' })).toBeVisible()
  await page.getByRole('textbox', { name: '新しいタスク' }).fill('買い物に行く')
  await page.getByRole('button', { name: 'タスクを追加' }).click()
  await expect(page.getByText('買い物に行く', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('買い物に行く', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '買い物に行くを編集' }).click()
  await page.getByRole('textbox', { name: 'タスク名' }).fill('牛乳を買う')
  await page.getByRole('button', { name: '変更を保存' }).click()
  await expect(page.getByText('牛乳を買う', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/todo-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/todo-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('checkbox', { name: '牛乳を買うを完了にする' }).click()
  await expect(page.getByRole('checkbox', { name: '牛乳を買うを未完了に戻す' })).toBeChecked()
  await page.getByRole('button', { name: '未完了', exact: true }).click()
  await expect(page.getByText('牛乳を買う', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: '完了', exact: true }).click()
  await expect(page.getByText('牛乳を買う', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'タスクを検索' }).fill('一致しない検索')
  await expect(page.getByText('条件に合うタスクはありません')).toBeVisible()
  await page.getByRole('textbox', { name: 'タスクを検索' }).clear()
  await page.getByRole('checkbox', { name: '牛乳を買うを未完了に戻す' }).click()
  await expect(page.getByRole('status')).toHaveText('未完了に戻しました')
  await page.getByRole('button', { name: 'すべて', exact: true }).click()
  await page.getByRole('button', { name: '牛乳を買うを削除' }).click()
  await page.getByRole('button', { name: '削除する', exact: true }).click()
  await expect(page.getByText('牛乳を買う', { exact: true })).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('まだタスクがありません')).toBeVisible()
})

test('recovers a failed loader when retry is pressed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '新しいタスク' }).fill('再取得を確認')
  await page.route('**/_serverFn/**', async (route) => {
    if (route.request().method() === 'GET') await route.abort('failed')
    else await route.continue()
  })
  await page.getByRole('button', { name: 'タスクを追加' }).click()
  await expect(page.getByRole('heading', { name: 'タスクを読み込めませんでした' })).toBeVisible()
  await page.unroute('**/_serverFn/**')
  await page.getByRole('button', { name: '再試行' }).click()
  await expect(page.getByText('再取得を確認', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '再取得を確認を削除' }).click()
  await page.getByRole('button', { name: '削除する', exact: true }).click()
  await expect(page.getByText('まだタスクがありません')).toBeVisible()
})
